server:
  port: 8083

spring:
  application:
    name: blog-app
  datasource:
    url: jdbc:h2:mem:blog_db
    username: sa
    password:
  sql:
    init:
      mode: embedded

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
